[package]
name = "py-holidays-rs"
version = "0.0.9"
edition = "2021"
authors = ["Billy Sheppard"]
license = "Apache-2.0"
keywords = ["holidays", "vacation", "dates"]
readme = "README.md"
description = "Public Holiday crate based on the python Holidays package"
repository = "https://github.com/Billy-Sheppard/py-holidays-rs"
homepage = "https://github.com/Billy-Sheppard/py-holidays-rs"

[dependencies]
ron = "0.10.1"
serde = { features = ["derive"], version = "1.0.219" }
chrono = { features = ["serde"], version = "0.4.41" }
flate2 = { version = "1.1.1" }

[build-dependencies]
flate2 = { version = "1.0.28" }

[features]
default = []
years = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(docs_rs)'] }