[package]
name = "py-holidays-rs"
version = "0.0.11"
edition = "2021"
authors = ["Billy Sheppard"]
license = "Apache-2.0"
keywords = ["holidays", "vacation", "dates"]
readme = "README.md"
description = "Public Holiday crate based on the python Holidays package"
repository = "https://github.com/Billy-Sheppard/py-holidays-rs"
homepage = "https://github.com/Billy-Sheppard/py-holidays-rs"

[dependencies]
serde_json = { features = ["std"], version = "1.0.142", default-features = false }
serde = { features = ["derive", "std"], version = "1.0.219", default-features = false }
chrono = { features = ["serde","std"], version = "0.4.41", default-features = false }
flate2 = { features = ["rust_backend"], version = "1.1.1" , default-features = false}

[build-dependencies]
flate2 = { features = ["rust_backend"], version = "1.1.1" , default-features = false}
serde_json = { features = ["std"], version = "1.0.142", default-features = false }

[features]
default = []
years = []

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(docs_rs)'] }
