[package]
name = "py-holidays-rs"
version = "0.0.2"
edition = "2021"
authors = ["Billy Sheppard"]
license = "Apache-2.0"
keywords = ["holidays", "vacation", "dates"]
readme = "README.md"
description = "Public Holiday crate based on the python Holidays package"
repository = "https://github.com/Billy-Sheppard/py-holidays-rs"
homepage = "https://github.com/Billy-Sheppard/py-holidays-rs"

[dependencies]
ron = "0.8"
serde = { features = ["derive"], version = "1" }
chrono = { features = ["serde"], version = "0.4" }
flate2 = { version = "1.0" }

[build-dependencies]
flate2 = { version = "1.0" }

[features]
default = []
years = []
