[package]
name = "py-holidays-rs"
version = "0.0.7"
edition = "2021"
authors = ["Billy Sheppard"]
license = "Apache-2.0"
keywords = ["holidays", "vacation", "dates"]
readme = "README.md"
description = "Public Holiday crate based on the python Holidays package"
repository = "https://github.com/Billy-Sheppard/py-holidays-rs"
homepage = "https://github.com/Billy-Sheppard/py-holidays-rs"

[dependencies]
ron = "0.8.1"
serde = { features = ["derive"], version = "1.0.197" }
chrono = { features = ["serde"], version = "0.4.35" }
flate2 = { version = "1.0.28" }

[build-dependencies]
flate2 = { version = "1.0.28" }

[features]
default = []
years = []
