[package]
name = "py-holidays-rs"
version = "0.0.1"
edition = "2021"
authors = ["Billy Sheppard"]
license = "Apache-2.0"
keywords = ["holidays", "vacation", "dates"]
readme = "README.md"
description = "Public Holiday crate based on the python Holidays package"
repository = "https://github.com/Billy-Sheppard/py-holidays-rs"
homepage = "https://github.com/Billy-Sheppard/py-holidays-rs"

[dependencies]
ron = "0.8"
serde = { features = ["derive"], version = "1" }
chrono = { features = ["serde"], version = "0.4" }
include-flate = "0.3"
zip = { default-features = false, features = ["deflate"], version = "0.6" }

[build-dependencies]
zip = { default-features = false, features = ["deflate"], version = "0.6" }

[features]
default = []
years = []
