use std::collections::BTreeMap;

use serde::{Deserialize, Serialize};

#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct Country {
    pub code: CountryCode,
    pub name: &'static str,
    pub subdivisions: &'static [SubDivision],
}
#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Deserialize, Serialize)]
pub enum CountryCode {
    AL,
    DZ,
    AS,
    AD,
    AO,
    AR,
    AM,
    AW,
    AU,
    AT,
    AZ,
    BS,
    BH,
    BD,
    BB,
    BY,
    BE,
    BZ,
    BO,
    BA,
    BW,
    BR,
    BN,
    BG,
    BF,
    BI,
    KH,
    CM,
    CA,
    TD,
    CL,
    CN,
    CO,
    CR,
    HR,
    CU,
    CW,
    CY,
    CZ,
    DK,
    DJ,
    DO,
    EC,
    EG,
    SV,
    EE,
    SZ,
    ET,
    FI,
    FR,
    GA,
    GE,
    DE,
    GR,
    GU,
    GT,
    HN,
    HK,
    HU,
    IS,
    IN,
    ID,
    IR,
    IE,
    IM,
    IL,
    IT,
    JM,
    JP,
    KZ,
    KE,
    KG,
    LA,
    LV,
    LS,
    LI,
    LT,
    LU,
    MG,
    MW,
    MY,
    MV,
    MT,
    MH,
    MX,
    MD,
    MC,
    ME,
    MA,
    MZ,
    NA,
    NL,
    NZ,
    NI,
    NG,
    MP,
    MK,
    NO,
    PK,
    PA,
    PG,
    PY,
    PE,
    PH,
    PL,
    PT,
    PR,
    RO,
    RU,
    SM,
    SA,
    RS,
    SG,
    SK,
    SI,
    ZA,
    KR,
    ES,
    SE,
    CH,
    TW,
    TZ,
    TH,
    TL,
    TO,
    TN,
    TR,
    UA,
    AE,
    GB,
    UM,
    US,
    UY,
    UZ,
    VU,
    VA,
    VE,
    VN,
    VI,
    ZM,
    ZW,
}

impl CountryCode {
    pub fn get_by_country_name(s: &str) -> Option<CountryCode> {
        match s {
            "Albania" => Some(CountryCode::AL),
            "Algeria" => Some(CountryCode::DZ),
            "American Samoa" => Some(CountryCode::AS),
            "Angola" => Some(CountryCode::AO),
            "Argentina" => Some(CountryCode::AR),
            "Armenia" => Some(CountryCode::AM),
            "Aruba" => Some(CountryCode::AW),
            "Azerbaijan" => Some(CountryCode::AZ),
            "Bahamas" => Some(CountryCode::BS),
            "Bahrain" => Some(CountryCode::BH),
            "Bangladesh" => Some(CountryCode::BD),
            "Barbados" => Some(CountryCode::BB),
            "Belarus" => Some(CountryCode::BY),
            "Belgium" => Some(CountryCode::BE),
            "Belize" => Some(CountryCode::BZ),
            "Bosnia and Herzegovina" => Some(CountryCode::BA),
            "Botswana" => Some(CountryCode::BW),
            "Brunei" => Some(CountryCode::BN),
            "Bulgaria" => Some(CountryCode::BG),
            "Burkina Faso" => Some(CountryCode::BF),
            "Burundi" => Some(CountryCode::BI),
            "Cambodia" => Some(CountryCode::KH),
            "Cameroon" => Some(CountryCode::CM),
            "Chad" => Some(CountryCode::TD),
            "China" => Some(CountryCode::CN),
            "Colombia" => Some(CountryCode::CO),
            "Costa Rica" => Some(CountryCode::CR),
            "Croatia" => Some(CountryCode::HR),
            "Cuba" => Some(CountryCode::CU),
            "Curacao" => Some(CountryCode::CW),
            "Cyprus" => Some(CountryCode::CY),
            "Czechia" => Some(CountryCode::CZ),
            "Denmark" => Some(CountryCode::DK),
            "Djibouti" => Some(CountryCode::DJ),
            "Dominican Republic" => Some(CountryCode::DO),
            "Ecuador" => Some(CountryCode::EC),
            "Egypt" => Some(CountryCode::EG),
            "Estonia" => Some(CountryCode::EE),
            "Eswatini" => Some(CountryCode::SZ),
            "Ethiopia" => Some(CountryCode::ET),
            "Finland" => Some(CountryCode::FI),
            "Gabon" => Some(CountryCode::GA),
            "Georgia" => Some(CountryCode::GE),
            "Greece" => Some(CountryCode::GR),
            "Guam" => Some(CountryCode::GU),
            "Guatemala" => Some(CountryCode::GT),
            "Honduras" => Some(CountryCode::HN),
            "Hong Kong" => Some(CountryCode::HK),
            "Hungary" => Some(CountryCode::HU),
            "Iceland" => Some(CountryCode::IS),
            "Indonesia" => Some(CountryCode::ID),
            "Iran" => Some(CountryCode::IR),
            "Ireland" => Some(CountryCode::IE),
            "Isle of Man" => Some(CountryCode::IM),
            "Israel" => Some(CountryCode::IL),
            "Jamaica" => Some(CountryCode::JM),
            "Japan" => Some(CountryCode::JP),
            "Kazakhstan" => Some(CountryCode::KZ),
            "Kenya" => Some(CountryCode::KE),
            "Kyrgyzstan" => Some(CountryCode::KG),
            "Laos" => Some(CountryCode::LA),
            "Latvia" => Some(CountryCode::LV),
            "Lesotho" => Some(CountryCode::LS),
            "Liechtenstein" => Some(CountryCode::LI),
            "Lithuania" => Some(CountryCode::LT),
            "Luxembourg" => Some(CountryCode::LU),
            "Madagascar" => Some(CountryCode::MG),
            "Malawi" => Some(CountryCode::MW),
            "Maldives" => Some(CountryCode::MV),
            "Malta" => Some(CountryCode::MT),
            "Marshall Islands" => Some(CountryCode::MH),
            "Mexico" => Some(CountryCode::MX),
            "Moldova" => Some(CountryCode::MD),
            "Monaco" => Some(CountryCode::MC),
            "Montenegro" => Some(CountryCode::ME),
            "Morocco" => Some(CountryCode::MA),
            "Mozambique" => Some(CountryCode::MZ),
            "Namibia" => Some(CountryCode::NA),
            "Netherlands" => Some(CountryCode::NL),
            "Nigeria" => Some(CountryCode::NG),
            "Northern Mariana Islands" => Some(CountryCode::MP),
            "North Macedonia" => Some(CountryCode::MK),
            "Norway" => Some(CountryCode::NO),
            "Pakistan" => Some(CountryCode::PK),
            "Panama" => Some(CountryCode::PA),
            "Papua New Guinea" => Some(CountryCode::PG),
            "Paraguay" => Some(CountryCode::PY),
            "Peru" => Some(CountryCode::PE),
            "Philippines" => Some(CountryCode::PH),
            "Poland" => Some(CountryCode::PL),
            "Puerto Rico" => Some(CountryCode::PR),
            "Romania" => Some(CountryCode::RO),
            "Russia" => Some(CountryCode::RU),
            "San Marino" => Some(CountryCode::SM),
            "Saudi Arabia" => Some(CountryCode::SA),
            "Serbia" => Some(CountryCode::RS),
            "Singapore" => Some(CountryCode::SG),
            "Slovakia" => Some(CountryCode::SK),
            "Slovenia" => Some(CountryCode::SI),
            "South Africa" => Some(CountryCode::ZA),
            "South Korea" => Some(CountryCode::KR),
            "Sweden" => Some(CountryCode::SE),
            "Taiwan" => Some(CountryCode::TW),
            "Tanzania" => Some(CountryCode::TZ),
            "Thailand" => Some(CountryCode::TH),
            "Timor Leste" => Some(CountryCode::TL),
            "Tonga" => Some(CountryCode::TO),
            "Tunisia" => Some(CountryCode::TN),
            "Turkey" => Some(CountryCode::TR),
            "Ukraine" => Some(CountryCode::UA),
            "United Arab Emirates" => Some(CountryCode::AE),
            "United Kingdom" => Some(CountryCode::GB),
            "United States Minor Outlying Islands" => Some(CountryCode::UM),
            "Uruguay" => Some(CountryCode::UY),
            "Uzbekistan" => Some(CountryCode::UZ),
            "Vanuatu" => Some(CountryCode::VU),
            "Vatican City" => Some(CountryCode::VA),
            "Venezuela" => Some(CountryCode::VE),
            "Vietnam" => Some(CountryCode::VN),
            "Virgin Islands (U.S.)" => Some(CountryCode::VI),
            "Zambia" => Some(CountryCode::ZM),
            "Zimbabwe" => Some(CountryCode::ZW),
            _ => None,
        }
    }

    pub fn list_subdivisions_by_country<'a>(country: CountryCode) -> &'a [SubDivision] {
        Self::list_subdivisions()
            .get(&country)
            .unwrap()
            .subdivisions
    }

    pub fn list_subdivisions() -> BTreeMap<CountryCode, Country> {
        BTreeMap::from([
            (
                CountryCode::AL,
                Country {
                    code: CountryCode::AL,
                    name: "Albania",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::DZ,
                Country {
                    code: CountryCode::DZ,
                    name: "Algeria",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::AS,
                Country {
                    code: CountryCode::AS,
                    name: "American Samoa",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::AD,
                Country {
                    code: CountryCode::AD,
                    name: "Andorra",
                    subdivisions: &[
                        SubDivision::National,
                        SubDivision::_02,
                        SubDivision::_03,
                        SubDivision::_04,
                        SubDivision::_05,
                        SubDivision::_06,
                        SubDivision::_07,
                        SubDivision::_08,
                    ],
                },
            ),
            (
                CountryCode::AO,
                Country {
                    code: CountryCode::AO,
                    name: "Angola",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::AR,
                Country {
                    code: CountryCode::AR,
                    name: "Argentina",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::AM,
                Country {
                    code: CountryCode::AM,
                    name: "Armenia",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::AW,
                Country {
                    code: CountryCode::AW,
                    name: "Aruba",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::AU,
                Country {
                    code: CountryCode::AU,
                    name: "Australia",
                    subdivisions: &[
                        SubDivision::National,
                        SubDivision::ACT,
                        SubDivision::NSW,
                        SubDivision::NT,
                        SubDivision::QLD,
                        SubDivision::SA,
                        SubDivision::TAS,
                        SubDivision::VIC,
                        SubDivision::WA,
                    ],
                },
            ),
            (
                CountryCode::AT,
                Country {
                    code: CountryCode::AT,
                    name: "Austria",
                    subdivisions: &[
                        SubDivision::National,
                        SubDivision::_1,
                        SubDivision::_2,
                        SubDivision::_3,
                        SubDivision::_4,
                        SubDivision::_5,
                        SubDivision::_6,
                        SubDivision::_7,
                        SubDivision::_8,
                        SubDivision::_9,
                    ],
                },
            ),
            (
                CountryCode::AZ,
                Country {
                    code: CountryCode::AZ,
                    name: "Azerbaijan",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::BS,
                Country {
                    code: CountryCode::BS,
                    name: "Bahamas",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::BH,
                Country {
                    code: CountryCode::BH,
                    name: "Bahrain",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::BD,
                Country {
                    code: CountryCode::BD,
                    name: "Bangladesh",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::BB,
                Country {
                    code: CountryCode::BB,
                    name: "Barbados",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::BY,
                Country {
                    code: CountryCode::BY,
                    name: "Belarus",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::BE,
                Country {
                    code: CountryCode::BE,
                    name: "Belgium",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::BZ,
                Country {
                    code: CountryCode::BZ,
                    name: "Belize",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::BO,
                Country {
                    code: CountryCode::BO,
                    name: "Bolivia",
                    subdivisions: &[
                        SubDivision::National,
                        SubDivision::B,
                        SubDivision::C,
                        SubDivision::H,
                        SubDivision::L,
                        SubDivision::N,
                        SubDivision::O,
                        SubDivision::P,
                        SubDivision::S,
                        SubDivision::T,
                    ],
                },
            ),
            (
                CountryCode::BA,
                Country {
                    code: CountryCode::BA,
                    name: "Bosnia and Herzegovina",
                    subdivisions: &[
                        SubDivision::National,
                        SubDivision::BIH,
                        SubDivision::BRC,
                        SubDivision::SRP,
                    ],
                },
            ),
            (
                CountryCode::BW,
                Country {
                    code: CountryCode::BW,
                    name: "Botswana",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::BR,
                Country {
                    code: CountryCode::BR,
                    name: "Brazil",
                    subdivisions: &[
                        SubDivision::National,
                        SubDivision::AC,
                        SubDivision::AL,
                        SubDivision::AM,
                        SubDivision::AP,
                        SubDivision::BA,
                        SubDivision::CE,
                        SubDivision::DF,
                        SubDivision::ES,
                        SubDivision::GO,
                        SubDivision::MA,
                        SubDivision::MG,
                        SubDivision::MS,
                        SubDivision::MT,
                        SubDivision::PA,
                        SubDivision::PB,
                        SubDivision::PE,
                        SubDivision::PI,
                        SubDivision::PR,
                        SubDivision::RJ,
                        SubDivision::RN,
                        SubDivision::RO,
                        SubDivision::RR,
                        SubDivision::RS,
                        SubDivision::SC,
                        SubDivision::SE,
                        SubDivision::SP,
                        SubDivision::TO,
                    ],
                },
            ),
            (
                CountryCode::BN,
                Country {
                    code: CountryCode::BN,
                    name: "Brunei",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::BG,
                Country {
                    code: CountryCode::BG,
                    name: "Bulgaria",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::BF,
                Country {
                    code: CountryCode::BF,
                    name: "Burkina Faso",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::BI,
                Country {
                    code: CountryCode::BI,
                    name: "Burundi",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::KH,
                Country {
                    code: CountryCode::KH,
                    name: "Cambodia",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::CM,
                Country {
                    code: CountryCode::CM,
                    name: "Cameroon",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::CA,
                Country {
                    code: CountryCode::CA,
                    name: "Canada",
                    subdivisions: &[
                        SubDivision::National,
                        SubDivision::AB,
                        SubDivision::BC,
                        SubDivision::MB,
                        SubDivision::NB,
                        SubDivision::NL,
                        SubDivision::NS,
                        SubDivision::NT,
                        SubDivision::NU,
                        SubDivision::ON,
                        SubDivision::PE,
                        SubDivision::QC,
                        SubDivision::SK,
                        SubDivision::YT,
                    ],
                },
            ),
            (
                CountryCode::TD,
                Country {
                    code: CountryCode::TD,
                    name: "Chad",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::CL,
                Country {
                    code: CountryCode::CL,
                    name: "Chile",
                    subdivisions: &[
                        SubDivision::National,
                        SubDivision::AI,
                        SubDivision::AN,
                        SubDivision::AP,
                        SubDivision::AR,
                        SubDivision::AT,
                        SubDivision::BI,
                        SubDivision::CO,
                        SubDivision::LI,
                        SubDivision::LL,
                        SubDivision::LR,
                        SubDivision::MA,
                        SubDivision::ML,
                        SubDivision::NB,
                        SubDivision::RM,
                        SubDivision::TA,
                        SubDivision::VS,
                    ],
                },
            ),
            (
                CountryCode::CN,
                Country {
                    code: CountryCode::CN,
                    name: "China",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::CO,
                Country {
                    code: CountryCode::CO,
                    name: "Colombia",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::CR,
                Country {
                    code: CountryCode::CR,
                    name: "Costa Rica",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::HR,
                Country {
                    code: CountryCode::HR,
                    name: "Croatia",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::CU,
                Country {
                    code: CountryCode::CU,
                    name: "Cuba",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::CW,
                Country {
                    code: CountryCode::CW,
                    name: "Curacao",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::CY,
                Country {
                    code: CountryCode::CY,
                    name: "Cyprus",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::CZ,
                Country {
                    code: CountryCode::CZ,
                    name: "Czechia",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::DK,
                Country {
                    code: CountryCode::DK,
                    name: "Denmark",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::DJ,
                Country {
                    code: CountryCode::DJ,
                    name: "Djibouti",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::DO,
                Country {
                    code: CountryCode::DO,
                    name: "Dominican Republic",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::EC,
                Country {
                    code: CountryCode::EC,
                    name: "Ecuador",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::EG,
                Country {
                    code: CountryCode::EG,
                    name: "Egypt",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::SV,
                Country {
                    code: CountryCode::SV,
                    name: "El Salvador",
                    subdivisions: &[
                        SubDivision::National,
                        SubDivision::AH,
                        SubDivision::CA,
                        SubDivision::CH,
                        SubDivision::CU,
                        SubDivision::LI,
                        SubDivision::MO,
                        SubDivision::PA,
                        SubDivision::SA,
                        SubDivision::SM,
                        SubDivision::SO,
                        SubDivision::SS,
                        SubDivision::SV,
                        SubDivision::UN,
                        SubDivision::US,
                    ],
                },
            ),
            (
                CountryCode::EE,
                Country {
                    code: CountryCode::EE,
                    name: "Estonia",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::SZ,
                Country {
                    code: CountryCode::SZ,
                    name: "Eswatini",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::ET,
                Country {
                    code: CountryCode::ET,
                    name: "Ethiopia",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::FI,
                Country {
                    code: CountryCode::FI,
                    name: "Finland",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::FR,
                Country {
                    code: CountryCode::FR,
                    name: "France",
                    subdivisions: &[
                        SubDivision::National,
                        SubDivision::BL,
                        SubDivision::GES,
                        SubDivision::GP,
                        SubDivision::GY,
                        SubDivision::MF,
                        SubDivision::MQ,
                        SubDivision::NC,
                        SubDivision::PF,
                        SubDivision::RE,
                        SubDivision::WF,
                        SubDivision::YT,
                    ],
                },
            ),
            (
                CountryCode::GA,
                Country {
                    code: CountryCode::GA,
                    name: "Gabon",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::GE,
                Country {
                    code: CountryCode::GE,
                    name: "Georgia",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::DE,
                Country {
                    code: CountryCode::DE,
                    name: "Germany",
                    subdivisions: &[
                        SubDivision::National,
                        SubDivision::BB,
                        SubDivision::BE,
                        SubDivision::BW,
                        SubDivision::BY,
                        SubDivision::BYP,
                        SubDivision::HB,
                        SubDivision::HE,
                        SubDivision::HH,
                        SubDivision::MV,
                        SubDivision::NI,
                        SubDivision::NW,
                        SubDivision::RP,
                        SubDivision::SH,
                        SubDivision::SL,
                        SubDivision::SN,
                        SubDivision::ST,
                        SubDivision::TH,
                    ],
                },
            ),
            (
                CountryCode::GR,
                Country {
                    code: CountryCode::GR,
                    name: "Greece",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::GU,
                Country {
                    code: CountryCode::GU,
                    name: "Guam",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::GT,
                Country {
                    code: CountryCode::GT,
                    name: "Guatemala",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::HN,
                Country {
                    code: CountryCode::HN,
                    name: "Honduras",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::HK,
                Country {
                    code: CountryCode::HK,
                    name: "Hong Kong",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::HU,
                Country {
                    code: CountryCode::HU,
                    name: "Hungary",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::IS,
                Country {
                    code: CountryCode::IS,
                    name: "Iceland",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::IN,
                Country {
                    code: CountryCode::IN,
                    name: "India",
                    subdivisions: &[
                        SubDivision::National,
                        SubDivision::AN,
                        SubDivision::AP,
                        SubDivision::AR,
                        SubDivision::AS,
                        SubDivision::BR,
                        SubDivision::CG,
                        SubDivision::CH,
                        SubDivision::DD,
                        SubDivision::DH,
                        SubDivision::DL,
                        SubDivision::GA,
                        SubDivision::GJ,
                        SubDivision::HP,
                        SubDivision::HR,
                        SubDivision::JH,
                        SubDivision::JK,
                        SubDivision::KA,
                        SubDivision::KL,
                        SubDivision::LA,
                        SubDivision::LD,
                        SubDivision::MH,
                        SubDivision::ML,
                        SubDivision::MN,
                        SubDivision::MP,
                        SubDivision::MZ,
                        SubDivision::NL,
                        SubDivision::OR,
                        SubDivision::PB,
                        SubDivision::PY,
                        SubDivision::RJ,
                        SubDivision::SK,
                        SubDivision::TN,
                        SubDivision::TR,
                        SubDivision::TS,
                        SubDivision::UK,
                        SubDivision::UP,
                        SubDivision::WB,
                    ],
                },
            ),
            (
                CountryCode::ID,
                Country {
                    code: CountryCode::ID,
                    name: "Indonesia",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::IR,
                Country {
                    code: CountryCode::IR,
                    name: "Iran",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::IE,
                Country {
                    code: CountryCode::IE,
                    name: "Ireland",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::IM,
                Country {
                    code: CountryCode::IM,
                    name: "Isle of Man",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::IL,
                Country {
                    code: CountryCode::IL,
                    name: "Israel",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::IT,
                Country {
                    code: CountryCode::IT,
                    name: "Italy",
                    subdivisions: &[
                        SubDivision::National,
                        SubDivision::AG,
                        SubDivision::AL,
                        SubDivision::AN,
                        SubDivision::AO,
                        SubDivision::AP,
                        SubDivision::AQ,
                        SubDivision::AR,
                        SubDivision::AT,
                        SubDivision::AV,
                        SubDivision::BA,
                        SubDivision::BG,
                        SubDivision::BI,
                        SubDivision::BL,
                        SubDivision::BN,
                        SubDivision::BO,
                        SubDivision::BR,
                        SubDivision::BS,
                        SubDivision::BT,
                        SubDivision::BZ,
                        SubDivision::CA,
                        SubDivision::CB,
                        SubDivision::CE,
                        SubDivision::CH,
                        SubDivision::CL,
                        SubDivision::CN,
                        SubDivision::CO,
                        SubDivision::CR,
                        SubDivision::CS,
                        SubDivision::CT,
                        SubDivision::CZ,
                        SubDivision::EN,
                        SubDivision::FC,
                        SubDivision::FE,
                        SubDivision::FG,
                        SubDivision::FI,
                        SubDivision::FM,
                        SubDivision::FR,
                        SubDivision::GE,
                        SubDivision::GO,
                        SubDivision::GR,
                        SubDivision::IM,
                        SubDivision::IS,
                        SubDivision::KR,
                        SubDivision::LC,
                        SubDivision::LE,
                        SubDivision::LI,
                        SubDivision::LO,
                        SubDivision::LT,
                        SubDivision::LU,
                        SubDivision::MB,
                        SubDivision::MC,
                        SubDivision::ME,
                        SubDivision::MI,
                        SubDivision::MN,
                        SubDivision::MO,
                        SubDivision::MS,
                        SubDivision::MT,
                        SubDivision::NA,
                        SubDivision::NO,
                        SubDivision::NU,
                        SubDivision::OR,
                        SubDivision::PA,
                        SubDivision::PC,
                        SubDivision::PD,
                        SubDivision::PE,
                        SubDivision::PG,
                        SubDivision::PI,
                        SubDivision::PN,
                        SubDivision::PO,
                        SubDivision::PR,
                        SubDivision::PT,
                        SubDivision::PU,
                        SubDivision::PV,
                        SubDivision::PZ,
                        SubDivision::RA,
                        SubDivision::RC,
                        SubDivision::RE,
                        SubDivision::RG,
                        SubDivision::RI,
                        SubDivision::RM,
                        SubDivision::RN,
                        SubDivision::RO,
                        SubDivision::SA,
                        SubDivision::SI,
                        SubDivision::SO,
                        SubDivision::SP,
                        SubDivision::SR,
                        SubDivision::SS,
                        SubDivision::SU,
                        SubDivision::SV,
                        SubDivision::TA,
                        SubDivision::TE,
                        SubDivision::TN,
                        SubDivision::TO,
                        SubDivision::TP,
                        SubDivision::TR,
                        SubDivision::TS,
                        SubDivision::TV,
                        SubDivision::UD,
                        SubDivision::VA,
                        SubDivision::VB,
                        SubDivision::VC,
                        SubDivision::VE,
                        SubDivision::VI,
                        SubDivision::VR,
                        SubDivision::VT,
                        SubDivision::VV,
                        SubDivision::Andria,
                        SubDivision::Barletta,
                        SubDivision::Cesena,
                        SubDivision::Forli,
                        SubDivision::Pesaro,
                        SubDivision::Trani,
                        SubDivision::Urbino,
                    ],
                },
            ),
            (
                CountryCode::JM,
                Country {
                    code: CountryCode::JM,
                    name: "Jamaica",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::JP,
                Country {
                    code: CountryCode::JP,
                    name: "Japan",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::KZ,
                Country {
                    code: CountryCode::KZ,
                    name: "Kazakhstan",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::KE,
                Country {
                    code: CountryCode::KE,
                    name: "Kenya",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::KG,
                Country {
                    code: CountryCode::KG,
                    name: "Kyrgyzstan",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::LA,
                Country {
                    code: CountryCode::LA,
                    name: "Laos",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::LV,
                Country {
                    code: CountryCode::LV,
                    name: "Latvia",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::LS,
                Country {
                    code: CountryCode::LS,
                    name: "Lesotho",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::LI,
                Country {
                    code: CountryCode::LI,
                    name: "Liechtenstein",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::LT,
                Country {
                    code: CountryCode::LT,
                    name: "Lithuania",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::LU,
                Country {
                    code: CountryCode::LU,
                    name: "Luxembourg",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::MG,
                Country {
                    code: CountryCode::MG,
                    name: "Madagascar",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::MW,
                Country {
                    code: CountryCode::MW,
                    name: "Malawi",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::MY,
                Country {
                    code: CountryCode::MY,
                    name: "Malaysia",
                    subdivisions: &[
                        SubDivision::National,
                        SubDivision::JHR,
                        SubDivision::KDH,
                        SubDivision::KTN,
                        SubDivision::KUL,
                        SubDivision::LBN,
                        SubDivision::MLK,
                        SubDivision::NSN,
                        SubDivision::PHG,
                        SubDivision::PJY,
                        SubDivision::PLS,
                        SubDivision::PNG,
                        SubDivision::PRK,
                        SubDivision::SBH,
                        SubDivision::SGR,
                        SubDivision::SWK,
                        SubDivision::TRG,
                    ],
                },
            ),
            (
                CountryCode::MV,
                Country {
                    code: CountryCode::MV,
                    name: "Maldives",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::MT,
                Country {
                    code: CountryCode::MT,
                    name: "Malta",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::MH,
                Country {
                    code: CountryCode::MH,
                    name: "Marshall Islands",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::MX,
                Country {
                    code: CountryCode::MX,
                    name: "Mexico",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::MD,
                Country {
                    code: CountryCode::MD,
                    name: "Moldova",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::MC,
                Country {
                    code: CountryCode::MC,
                    name: "Monaco",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::ME,
                Country {
                    code: CountryCode::ME,
                    name: "Montenegro",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::MA,
                Country {
                    code: CountryCode::MA,
                    name: "Morocco",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::MZ,
                Country {
                    code: CountryCode::MZ,
                    name: "Mozambique",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::NA,
                Country {
                    code: CountryCode::NA,
                    name: "Namibia",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::NL,
                Country {
                    code: CountryCode::NL,
                    name: "Netherlands",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::NZ,
                Country {
                    code: CountryCode::NZ,
                    name: "New Zealand",
                    subdivisions: &[
                        SubDivision::National,
                        SubDivision::AUK,
                        SubDivision::BOP,
                        SubDivision::CAN,
                        SubDivision::CIT,
                        SubDivision::GIS,
                        SubDivision::HKB,
                        SubDivision::MBH,
                        SubDivision::MWT,
                        SubDivision::NSN,
                        SubDivision::NTL,
                        SubDivision::OTA,
                        SubDivision::STL,
                        SubDivision::TAS,
                        SubDivision::TKI,
                        SubDivision::WGN,
                        SubDivision::WKO,
                        SubDivision::WTC,
                    ],
                },
            ),
            (
                CountryCode::NI,
                Country {
                    code: CountryCode::NI,
                    name: "Nicaragua",
                    subdivisions: &[
                        SubDivision::National,
                        SubDivision::AN,
                        SubDivision::AS,
                        SubDivision::BO,
                        SubDivision::CA,
                        SubDivision::CI,
                        SubDivision::CO,
                        SubDivision::ES,
                        SubDivision::GR,
                        SubDivision::JI,
                        SubDivision::LE,
                        SubDivision::MD,
                        SubDivision::MN,
                        SubDivision::MS,
                        SubDivision::MT,
                        SubDivision::NS,
                        SubDivision::RI,
                        SubDivision::SJ,
                    ],
                },
            ),
            (
                CountryCode::NG,
                Country {
                    code: CountryCode::NG,
                    name: "Nigeria",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::MP,
                Country {
                    code: CountryCode::MP,
                    name: "Northern Mariana Islands",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::MK,
                Country {
                    code: CountryCode::MK,
                    name: "North Macedonia",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::NO,
                Country {
                    code: CountryCode::NO,
                    name: "Norway",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::PK,
                Country {
                    code: CountryCode::PK,
                    name: "Pakistan",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::PA,
                Country {
                    code: CountryCode::PA,
                    name: "Panama",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::PG,
                Country {
                    code: CountryCode::PG,
                    name: "Papua New Guinea",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::PY,
                Country {
                    code: CountryCode::PY,
                    name: "Paraguay",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::PE,
                Country {
                    code: CountryCode::PE,
                    name: "Peru",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::PH,
                Country {
                    code: CountryCode::PH,
                    name: "Philippines",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::PL,
                Country {
                    code: CountryCode::PL,
                    name: "Poland",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::PT,
                Country {
                    code: CountryCode::PT,
                    name: "Portugal",
                    subdivisions: &[
                        SubDivision::National,
                        SubDivision::_01,
                        SubDivision::_02,
                        SubDivision::_03,
                        SubDivision::_04,
                        SubDivision::_05,
                        SubDivision::_06,
                        SubDivision::_07,
                        SubDivision::_08,
                        SubDivision::_09,
                        SubDivision::_10,
                        SubDivision::_11,
                        SubDivision::_12,
                        SubDivision::_13,
                        SubDivision::_14,
                        SubDivision::_15,
                        SubDivision::_16,
                        SubDivision::_17,
                        SubDivision::_18,
                        SubDivision::_20,
                        SubDivision::_30,
                    ],
                },
            ),
            (
                CountryCode::PR,
                Country {
                    code: CountryCode::PR,
                    name: "Puerto Rico",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::RO,
                Country {
                    code: CountryCode::RO,
                    name: "Romania",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::RU,
                Country {
                    code: CountryCode::RU,
                    name: "Russia",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::SM,
                Country {
                    code: CountryCode::SM,
                    name: "San Marino",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::SA,
                Country {
                    code: CountryCode::SA,
                    name: "Saudi Arabia",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::RS,
                Country {
                    code: CountryCode::RS,
                    name: "Serbia",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::SG,
                Country {
                    code: CountryCode::SG,
                    name: "Singapore",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::SK,
                Country {
                    code: CountryCode::SK,
                    name: "Slovakia",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::SI,
                Country {
                    code: CountryCode::SI,
                    name: "Slovenia",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::ZA,
                Country {
                    code: CountryCode::ZA,
                    name: "South Africa",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::KR,
                Country {
                    code: CountryCode::KR,
                    name: "South Korea",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::ES,
                Country {
                    code: CountryCode::ES,
                    name: "Spain",
                    subdivisions: &[
                        SubDivision::National,
                        SubDivision::AN,
                        SubDivision::AR,
                        SubDivision::AS,
                        SubDivision::CB,
                        SubDivision::CE,
                        SubDivision::CL,
                        SubDivision::CM,
                        SubDivision::CN,
                        SubDivision::CT,
                        SubDivision::EX,
                        SubDivision::GA,
                        SubDivision::IB,
                        SubDivision::MC,
                        SubDivision::MD,
                        SubDivision::ML,
                        SubDivision::NC,
                        SubDivision::PV,
                        SubDivision::RI,
                        SubDivision::VC,
                    ],
                },
            ),
            (
                CountryCode::SE,
                Country {
                    code: CountryCode::SE,
                    name: "Sweden",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::CH,
                Country {
                    code: CountryCode::CH,
                    name: "Switzerland",
                    subdivisions: &[
                        SubDivision::National,
                        SubDivision::AG,
                        SubDivision::AR,
                        SubDivision::AI,
                        SubDivision::BL,
                        SubDivision::BS,
                        SubDivision::BE,
                        SubDivision::FR,
                        SubDivision::GE,
                        SubDivision::GL,
                        SubDivision::GR,
                        SubDivision::JU,
                        SubDivision::LU,
                        SubDivision::NE,
                        SubDivision::NW,
                        SubDivision::OW,
                        SubDivision::SG,
                        SubDivision::SH,
                        SubDivision::SZ,
                        SubDivision::SO,
                        SubDivision::TG,
                        SubDivision::TI,
                        SubDivision::UR,
                        SubDivision::VD,
                        SubDivision::VS,
                        SubDivision::ZG,
                        SubDivision::ZH,
                    ],
                },
            ),
            (
                CountryCode::TW,
                Country {
                    code: CountryCode::TW,
                    name: "Taiwan",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::TZ,
                Country {
                    code: CountryCode::TZ,
                    name: "Tanzania",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::TH,
                Country {
                    code: CountryCode::TH,
                    name: "Thailand",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::TL,
                Country {
                    code: CountryCode::TL,
                    name: "Timor Leste",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::TO,
                Country {
                    code: CountryCode::TO,
                    name: "Tonga",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::TN,
                Country {
                    code: CountryCode::TN,
                    name: "Tunisia",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::TR,
                Country {
                    code: CountryCode::TR,
                    name: "Turkey",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::UA,
                Country {
                    code: CountryCode::UA,
                    name: "Ukraine",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::AE,
                Country {
                    code: CountryCode::AE,
                    name: "United Arab Emirates",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::GB,
                Country {
                    code: CountryCode::GB,
                    name: "United Kingdom",
                    subdivisions: &[
                        SubDivision::National,
                        SubDivision::ENG,
                        SubDivision::NIR,
                        SubDivision::SCT,
                        SubDivision::WLS,
                    ],
                },
            ),
            (
                CountryCode::UM,
                Country {
                    code: CountryCode::UM,
                    name: "United States Minor Outlying Islands",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::US,
                Country {
                    code: CountryCode::US,
                    name: "United States of America",
                    subdivisions: &[
                        SubDivision::National,
                        SubDivision::AK,
                        SubDivision::AL,
                        SubDivision::AR,
                        SubDivision::AS,
                        SubDivision::AZ,
                        SubDivision::CA,
                        SubDivision::CO,
                        SubDivision::CT,
                        SubDivision::DC,
                        SubDivision::DE,
                        SubDivision::FL,
                        SubDivision::GA,
                        SubDivision::GU,
                        SubDivision::HI,
                        SubDivision::IA,
                        SubDivision::ID,
                        SubDivision::IL,
                        SubDivision::IN,
                        SubDivision::KS,
                        SubDivision::KY,
                        SubDivision::LA,
                        SubDivision::MA,
                        SubDivision::MD,
                        SubDivision::ME,
                        SubDivision::MI,
                        SubDivision::MN,
                        SubDivision::MO,
                        SubDivision::MP,
                        SubDivision::MS,
                        SubDivision::MT,
                        SubDivision::NC,
                        SubDivision::ND,
                        SubDivision::NE,
                        SubDivision::NH,
                        SubDivision::NJ,
                        SubDivision::NM,
                        SubDivision::NV,
                        SubDivision::NY,
                        SubDivision::OH,
                        SubDivision::OK,
                        SubDivision::OR,
                        SubDivision::PA,
                        SubDivision::PR,
                        SubDivision::RI,
                        SubDivision::SC,
                        SubDivision::SD,
                        SubDivision::TN,
                        SubDivision::TX,
                        SubDivision::UM,
                        SubDivision::UT,
                        SubDivision::VA,
                        SubDivision::VI,
                        SubDivision::VT,
                        SubDivision::WA,
                        SubDivision::WI,
                        SubDivision::WV,
                        SubDivision::WY,
                    ],
                },
            ),
            (
                CountryCode::UY,
                Country {
                    code: CountryCode::UY,
                    name: "Uruguay",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::UZ,
                Country {
                    code: CountryCode::UZ,
                    name: "Uzbekistan",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::VU,
                Country {
                    code: CountryCode::VU,
                    name: "Vanuatu",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::VA,
                Country {
                    code: CountryCode::VA,
                    name: "Vatican City",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::VE,
                Country {
                    code: CountryCode::VE,
                    name: "Venezuela",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::VN,
                Country {
                    code: CountryCode::VN,
                    name: "Vietnam",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::VI,
                Country {
                    code: CountryCode::VI,
                    name: "Virgin Islands (U.S.)",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::ZM,
                Country {
                    code: CountryCode::ZM,
                    name: "Zambia",
                    subdivisions: &[],
                },
            ),
            (
                CountryCode::ZW,
                Country {
                    code: CountryCode::ZW,
                    name: "Zimbabwe",
                    subdivisions: &[],
                },
            ),
        ])
    }
}

#[derive(Debug, Copy, Clone, PartialEq, Eq, PartialOrd, Ord, Hash, Deserialize, Serialize)]
pub enum SubDivision {
    _01,
    _02,
    _03,
    _04,
    _05,
    _06,
    _07,
    _08,
    _09,
    _1,
    _10,
    _11,
    _12,
    _13,
    _14,
    _15,
    _16,
    _17,
    _18,
    _2,
    _20,
    _3,
    _30,
    _4,
    _5,
    _6,
    _7,
    _8,
    _9,
    AB,
    AC,
    ACT,
    AG,
    AH,
    AI,
    AK,
    AL,
    AM,
    AN,
    Andria,
    AO,
    AP,
    AQ,
    AR,
    AS,
    AT,
    AUK,
    AV,
    AZ,
    B,
    BA,
    Barletta,
    BB,
    BC,
    BE,
    BG,
    BI,
    BIH,
    BL,
    BN,
    BO,
    BOP,
    BR,
    BRC,
    BS,
    BT,
    BW,
    BY,
    BYP,
    BZ,
    C,
    CA,
    CAN,
    CB,
    CE,
    Cesena,
    CG,
    CH,
    CI,
    CIT,
    CL,
    CM,
    CN,
    CO,
    CR,
    CS,
    CT,
    CU,
    CZ,
    DC,
    DD,
    DE,
    DF,
    DH,
    DL,
    EN,
    ENG,
    ES,
    EX,
    FC,
    FE,
    FG,
    FI,
    FL,
    FM,
    Forli,
    FR,
    GA,
    GE,
    GES,
    GIS,
    GJ,
    GL,
    GO,
    GP,
    GR,
    GU,
    GY,
    H,
    HB,
    HE,
    HH,
    HI,
    HKB,
    HP,
    HR,
    IA,
    IB,
    ID,
    IL,
    IM,
    IN,
    IS,
    JH,
    JHR,
    JI,
    JK,
    JU,
    KA,
    KDH,
    KL,
    KR,
    KS,
    KTN,
    KUL,
    KY,
    L,
    LA,
    LBN,
    LC,
    LD,
    LE,
    LI,
    LL,
    LO,
    LR,
    LT,
    LU,
    MA,
    MB,
    MBH,
    MC,
    MD,
    ME,
    MF,
    MG,
    MH,
    MI,
    ML,
    MLK,
    MN,
    MO,
    MP,
    MQ,
    MS,
    MT,
    MV,
    MWT,
    MZ,
    N,
    NA,
    National,
    NB,
    NC,
    ND,
    NE,
    NH,
    NI,
    NIR,
    NJ,
    NL,
    NM,
    NO,
    NS,
    NSN,
    NSW,
    NT,
    NTL,
    NU,
    NV,
    NW,
    NY,
    O,
    OH,
    OK,
    ON,
    OR,
    OTA,
    OW,
    P,
    PA,
    PB,
    PC,
    PD,
    PE,
    Pesaro,
    PF,
    PG,
    PHG,
    PI,
    PJY,
    PLS,
    PN,
    PNG,
    PO,
    PR,
    PRK,
    PT,
    PU,
    PV,
    PY,
    PZ,
    QC,
    QLD,
    RA,
    RC,
    RE,
    RG,
    RI,
    RJ,
    RM,
    RN,
    RO,
    RP,
    RR,
    RS,
    S,
    SA,
    SBH,
    SC,
    SCT,
    SD,
    SE,
    SG,
    SGR,
    SH,
    SI,
    SJ,
    SK,
    SL,
    SM,
    SN,
    SO,
    SP,
    SR,
    SRP,
    SS,
    ST,
    STL,
    SU,
    SV,
    SWK,
    SZ,
    T,
    TA,
    TAS,
    TE,
    TG,
    TH,
    TI,
    TKI,
    TN,
    TO,
    TP,
    TR,
    Trani,
    TRG,
    TS,
    TV,
    TX,
    UD,
    UK,
    UM,
    UN,
    UP,
    UR,
    Urbino,
    US,
    UT,
    VA,
    VB,
    VC,
    VD,
    VE,
    VI,
    VIC,
    VR,
    VS,
    VT,
    VV,
    WA,
    WB,
    WF,
    WGN,
    WI,
    WKO,
    WLS,
    WTC,
    WV,
    WY,
    YT,
    ZG,
    ZH,
}
