name: Run `gen_holidays.py`

on:
  schedule:
    - cron: '0 19 * * *'  # 6 AM Australia/Melbourne time (UTC+10/11)
  push:
    branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  run-python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # needed for pushing changes

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        run: python gen_holidays.py

      - name: Minify and gzip JSON files
        run: python minify_and_gzip.py

      - name: Commit and push changes if any
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add ./files/*.json.gz ./all_holidays.json.gz
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update holiday JSON files [auto commit]"
            git push
          fi
